/** Mutuas con cuadro médico disponible (espejo de AVAILABLE_MUTUAS en SearchForm). */
export const MUTUAS = [
  "Adeslas",
  "Allianz",
  "Asisa",
  "AXA Salud",
  "Caser Salud",
  "Cigna",
  "DKV",
  "Divina Pastora",
  "Fiatc",
  "Generali",
  "IMQ",
  "Mapfre",
  "MUFACE",
  "Occidente",
  "Sanitas",
] as const;

/** Especialidades del desplegable (espejo de ESPECIALIDADES en SearchForm). */
export const ESPECIALIDADES = [
  "Alergología",
  "Andrología",
  "Aparato digestivo",
  "Cardiología",
  "Cirugía general",
  "Cirugía plástica",
  "Dermatología",
  "Endocrinología",
  "Fisioterapia",
  "Ginecología",
  "Hematología",
  "Logopedia",
  "Medicina de urgencias",
  "Medicina estética",
  "Medicina general",
  "Medicina interna",
  "Nefrología",
  "Neumología",
  "Neurocirugía",
  "Neurología",
  "Nutrición y dietética",
  "Odontología",
  "Oftalmología",
  "Oncología",
  "Otorrinolaringología",
  "Pediatría",
  "Podología",
  "Psicología",
  "Psiquiatría",
  "Rehabilitación",
  "Reumatología",
  "Traumatología",
  "Urología",
] as const;
